# Jekyll config file http://jekyllrb.com/docs/configuration/

# ----------------------------------------------------------------------
# | Build settings                                                     |
# ----------------------------------------------------------------------

encoding:      "utf-8"
timezone:      Asia/Kathmandu
locale:        en_us
markdown:      kramdown
kramdown:
  toc_levels:  1..3
highlighter:   pygments

# Permalink structure, see http://jekyllrb.com/docs/permalinks/
permalink:     /:year/:title/

paginate_path: /writings/page:num/
paginate:      10

# Collections
collections:
  docs:
    output: true
    permalink: /docs/:path/

# Front matter defaults
defaults:
  -
    scope:
      path: ""
      type: "posts"
    values:
      layout: "post"
      comments: "true"
  -
    scope:
      path: ""
      type: "docs"
    values:
      layout: "page"
      comments: "false"

# Files to exclude
exclude:
  - README.md
  - LICENSE
  - CNAME
  - Gemfile
  - Gemfile.lock
  - src
  - node_modules
  - package.json
  - Gruntfile.js
  - vendor
  - bower.json

# Plugins
gems:
  - jekyll-feed
#  - jekyll-mentions
  - jekyll-redirect-from
  - jekyll-sitemap
  - jemoji

# jekyll-mentions:
#  base_url: https://twitter.com

# Compress HTML
compress_html:
  clippings: all
  comments: all
  endings: all
  profile: false


# URL of site, include http://, do not include a trailing slash
url:                   http://xiangyingchang.com

# Site settings
title:                 向应昌
description:           "Good things take time and patience."
icon:                  "/assets/img/m-icon-white-on-blue.png"
header_image:          "/assets/img/home-bg.jpg"
author:
  name:                向应昌
  url:                 http://goo.gl/NNDGA8
  email:               lovecvoice@gmail.com
  twitter:             xiangyingchang
  googleplus:          应昌
  github:              xiangyingchang
  tumblr:              481550482
  linkedin:            lovecvoice
  facebook:            lovecvoice
ga_trackid:            "UA-60129317-1"
fb_admins:             
disqus_shortname:      向应昌
